---
# tasks file for tools_docker
- name: "install de package"
  apt:
   name: "{{ item }}"
   update_cache: yes
   state: present
  with_items:
    - tree
    - ca-certificates
    - curl 
    - gnupg
    - lsb-release
    - python3-docker

#- name: "Add Docker’s official GPG key"
#  shell:
#    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "set up the stable repository"
  shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: "install de package docker (ce/ce-cli/container.io)"
  apt:
   name: "{{ item }}"
   update_cache: yes
   state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
